title: anjana rajagopal
description: AI/ML engineer. graph learner. cyclist. chronically online.
url: "https://anjipoo.github.io"
baseurl: ""

author:
  name: Anjana Rajagopal
  email: anjanarajagopal2004@gmail.com
  github: anjipoo
  linkedin: anjana-r-9b16382a4

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules